### ISSUE TITLE
DEA compatibility test fails if there are no DEA instances

### ISSUE THREAD

**Issue by skibum55** [cloudfoundry-incubator/diego-acceptance-tests#3]
The DEA compatibility test fails if there are no DEA instances.  Can we please add a condition that skips this test (diego-acceptance-tests/diego/dea_compatibility_test.go) if there are zero DEA's.

**Comment by skibum55** [comment]
If there are no DEA's, when you start the pushed app you get the following:
```[ec2-user@bosh-jump bosh]$ cf start spring-music
Starting app spring-music in org sean / space development as admin...
FAILED
Server error, status code: 503, error code: 150003, message: One or more instances could not be started because of insufficient running resources.```
We can't really trap on this because it could be returned due to DEA or Diego constraints/quotas also.
Might be better to just put in a _skip_ at the run level or a bosh errand.

**Comment by skibum55** [comment]
I'm going to close this and put a pull request in to the diego-release to add a skip in https://github.com/cloudfoundry-incubator/diego-release/blob/develop/jobs/acceptance-tests/templates/run.erb#L26 and a variable at https://github.com/cloudfoundry-incubator/diego-release/blob/develop/manifest-generation/diego-acceptance-tests.yml

**Comment by ematpl** [comment]
Hi, @skibum55,

If you know you have no DEAs in the deployment, you can tell the DATs test suite to skip the tests in https://github.com/cloudfoundry-incubator/diego-acceptance-tests/blob/master/diego/dea_compatibility_test.go with a ginkgo option of the form `-skip="DEA Compatibility"`. You can also provide that `-skip` argument to the DATs errand in via the [`acceptance_tests.skip_regex` BOSH property in diego-release](https://github.com/cloudfoundry-incubator/diego-release/blob/develop/jobs/acceptance-tests/spec#L45-L47).

I see you just submitted https://github.com/cloudfoundry-incubator/diego-release/pull/115, but I don't think that approach works, since those DEA-compatibility tests aren't in a separate package in the DATs test suite. Is the configurability with the `acceptance_tests.skip_regex` property good enough?

Thanks,
Eric, CF Runtime Diego PM
